apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-do2t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-do2t
    app.kubernetes.io/part-of: e2e-golang
  name: devfile-sample-go-basic-do2t
  namespace: e2e-demos-uoba-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-do2t
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-do2t
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images-protected@sha256:842b32f91f50cf8a50a1f39bf21e702299ce97fe8a66a6e53e7ca95ee116bac9
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
